USE SISTEMA_AVIACAO;

/* LISTAGEM DE AERONAVES ORDENADAS POR TIPO */
SELECT
	AERONAVE.TIPO AS 'Tipo',
    AERONAVE.MODELO as 'Modelo',
    COMPANIA_AEREA.NOME AS 'Compania Aérea'
FROM AERONAVE JOIN COMPANIA_AEREA ON AERONAVE.FK_ID_COMPANIA_AEREA = COMPANIA_AEREA.ID
ORDER BY TIPO;

/* RELATÓRIO DE VÔOS DAS AERONAVES POR PERIODO */
SELECT 
    VOO.HORARIO_PARTIDA AS 'Partida',
    VOO.HORARIO_CHEGADA AS 'Chegada',
    AERONAVE.MODELO AS 'Modelo',
    COMPANIA_AEREA.NOME AS 'Compania Aérea',
    AEROPORTO_PARTIDA.NOME AS 'Aeroporto de Partida',
    AEROPORTO_CHEGADA.NOME AS 'Aeroporto de Chegada'
FROM VOO JOIN AERONAVE ON VOO.FK_ID_AERONAVE = AERONAVE.ID
JOIN COMPANIA_AEREA ON AERONAVE.FK_ID_COMPANIA_AEREA = COMPANIA_AEREA.ID JOIN AEROPORTO AEROPORTO_PARTIDA ON VOO.FK_ID_AEROPORTO_PARTIDA = AEROPORTO_PARTIDA.ID
JOIN AEROPORTO AEROPORTO_CHEGADA ON VOO.FK_ID_AEROPORTO_CHEGADA = AEROPORTO_CHEGADA.ID
ORDER BY VOO.HORARIO_PARTIDA;
    
/* RELATÓRIO DE VÔOS QUE FAZEM ESCALA EM UM DETERMINADO LOCAL */
SELECT 
    VOO.ID AS 'ID do Vôo',
    AEROPORTO_CHEGADA.NOME AS 'Destino',
    AEROPORTO_ESCALA.NOME AS 'Nome do Aeroporto de Escala'
FROM VOO 
JOIN ESCALA ON VOO.FK_ID_ESCALA = ESCALA.ID
JOIN AEROPORTO AEROPORTO_ESCALA ON ESCALA.FK_ID_AEROPORTO_SAIDA = AEROPORTO_ESCALA.ID
JOIN AEROPORTO AEROPORTO_CHEGADA ON VOO.FK_ID_AEROPORTO_CHEGADA = AEROPORTO_CHEGADA.ID
WHERE AEROPORTO_ESCALA.NOME = 'Aeroporto Internacional Guarulhos'
ORDER BY VOO.ID;

/* RELATÓRIO DE POLTRONAS DISPONÍVEIS EM X AVIÃO */
SELECT 
    POLTRONA.ID AS 'Poltrona',
	AERONAVE.MODELO AS 'Aeronave',
    CASE 
        WHEN POLTRONA.ESTA_VAGA = 1 THEN 'Sim' ELSE 'Não'
    END AS 'Poltrona Vaga?',
    POLTRONA.LOCALIZACAO AS 'Localização'
FROM AERONAVE
JOIN POLTRONA ON POLTRONA.FK_ID_AERONAVE = AERONAVE.ID
WHERE AERONAVE.ID = 2
ORDER BY AERONAVE.ID ASC;