USE SISTEMA_AVIACAO;

-- COMPANIAS AÉREAS
INSERT INTO COMPANIA_AEREA (NOME) VALUES ('Embraer');
INSERT INTO COMPANIA_AEREA (NOME) VALUES ('LATAM');
INSERT INTO COMPANIA_AEREA (NOME) VALUES ('Joãozinho Aviões');

/* --------------------------------------------------[AERONAVES]-------------------------------------------------- */
INSERT INTO AERONAVE (TIPO, MODELO, ID_COMPANIA_AEREA) VALUES (3, 'Legacy 650', 1); -- JATO, AERONAVE 1
INSERT INTO AERONAVE (TIPO, MODELO, ID_COMPANIA_AEREA) VALUES (2, 'Boeing 737', 2); -- AVIÃO, AERONAVE 2
INSERT INTO AERONAVE (TIPO, MODELO, ID_COMPANIA_AEREA) VALUES (1, 'Mirocopter SCH-2A', 3); -- HELICÓPTERO, AERONAVE 3
INSERT INTO AERONAVE (TIPO, MODELO, ID_COMPANIA_AEREA) VALUES (2, 'Boeing 777', 2); -- AVIÃO, AERONAVE 4

/* --------------------------------------------------[POLTRONAS]-------------------------------------------------- */
/* AERONAVE 01 --------------------------------------------------------------------------------------------------- */
-- PRIMEIRA CLASSE (1 FILEIRA)
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (2, TRUE, 1, 1); -- PRIMEIRA CLASSE, VAGA, JANELA, AERONAVE 1
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (2, TRUE, 2, 1); -- PRIMEIRA CLASSE, VAGA, CORREDOR, AERONAVE 1
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (2, TRUE, 5, 1); -- PRIMEIRA CLASSE, VAGA, CENTRO, AERONAVE 1
-- CLASSE LUXO (1 FILEIRA)
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (3, TRUE, 1, 1); -- LUXO, VAGA, JANELA, AERONAVE 1
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (3, TRUE, 2, 1); -- LUXO, VAGA, CORREDOR, AERONAVE 1
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (3, TRUE, 3, 1); -- LUXO, VAGA, CENTRO, AERONAVE 1

/* AERONAVE 02 --------------------------------------------------------------------------------------------------- */
-- CLASSE ECONÔMICA (3 FILEIRAS)
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 1, 2); -- ECONÔMICA, VAGA, JANELA, AERONAVE 2
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 2, 2); -- ECONÔMICA, VAGA, CORREDOR, AERONAVE 2
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 1, 2); -- ECONÔMICA, VAGA, JANELA, AERONAVE 2
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 2, 2); -- ECONÔMICA, VAGA, CORREDOR, AERONAVE 2
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 1, 2); -- ECONÔMICA, VAGA, JANELA, AERONAVE 2
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 2, 2); -- ECONÔMICA, VAGA, CORREDOR, AERONAVE 2
-- PRIMEIRA CLASSE (1 FILEIRA)
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (2, TRUE, 1, 2); -- PRIMEIRA CLASSE, VAGA, JANELA, AERONAVE 2
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (2, TRUE, 2, 2); -- PRIMEIRA CLASSE, VAGA, CORREDOR, AERONAVE 2
/* AERONAVE 03 ---------------------------------------------------------------------------------------------------- */
-- CLASSE ECONÔMICA (1 FILEIRA)
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 3, 3); -- ECONÔMICA, VAGA, DIREITA, AERONAVE 3
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 4, 3); -- ECONÔMICA, VAGA, ESQUERDA, AERONAVE 3
/* AERONAVE 04 ---------------------------------------------------------------------------------------------------- */
-- CLASSE ECONÔMICA (1 FILEIRA)
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 3, 4); -- ECONÔMICA, VAGA, DIREITA, AERONAVE 3
INSERT INTO POLTRONA (CLASSE, ESTA_VAGA, LOCALIZACAO, ID_AERONAVE) VALUES (1, TRUE, 4, 4); -- ECONÔMICA, VAGA, ESQUERDA, AERONAVE 3


/* --------------------------------------------------[AEROPORTOS]-------------------------------------------------- */
INSERT INTO AEROPORTO (NOME, CIDADE, ESTADO, PAIS) VALUES ('Aeroporto de Congonhas', 'São Paulo', 'SP', 'Brasil');
INSERT INTO AEROPORTO (NOME, CIDADE, ESTADO, PAIS) VALUES ('Aeroporto Internacional Guarulhos', 'Guarulhos', 'SP', 'Brasil');
INSERT INTO AEROPORTO (NOME, CIDADE, ESTADO, PAIS) VALUES ('Aeroporto Santos Dumont', 'Rio de Janeiro', 'RJ', 'Brasil');
INSERT INTO AEROPORTO (NOME, CIDADE, ESTADO, PAIS) VALUES ('Aeroporto Internacional Guararapes', 'Recife', 'PE', 'Brasil');
INSERT INTO AEROPORTO (NOME, CIDADE, ESTADO, PAIS) VALUES ('Aeroporto de Videira', 'Videira', 'SC', 'Brasil');

/* ---------------------------------------------------[CLIENTES]--------------------------------------------------- */
INSERT INTO CLIENTE (TIPO_CLIENTE, NOME, TELEFONE, PREFERENCIAL) VALUES (1, 'Guilherme Schweitzer', '49-99999-9999', TRUE);
INSERT INTO CLIENTE (TIPO_CLIENTE, NOME, TELEFONE, PREFERENCIAL) VALUES (2, 'Layne Firmino', '49-99999-9999', TRUE);
INSERT INTO CLIENTE (TIPO_CLIENTE, NOME, TELEFONE, PREFERENCIAL) VALUES (2, 'Alex Oneda', '49-99999-9999', FALSE);
INSERT INTO CLIENTE (TIPO_CLIENTE, NOME, TELEFONE, PREFERENCIAL) VALUES (1, 'Rafaela Correa', '49-99999-9999', FALSE);

/* -----------------------------------------------------[VÔOS]----------------------------------------------------- */
INSERT INTO VOO (ID_AERONAVE, ID_AEROPORTO_PARTIDA, ID_AEROPORTO_CHEGADA, HORARIO_PARTIDA, HORARIO_CHEGADA)
	VALUES (1, 1, 4, '2024-01-18 07:00:00', '2024-01-18 14:00:00');
INSERT INTO VOO (ID_AERONAVE, ID_AEROPORTO_PARTIDA, ID_AEROPORTO_CHEGADA, HORARIO_PARTIDA, HORARIO_CHEGADA)
	VALUES (2, 2, 3, '2024-01-19 12:00:00', '2024-01-19 14:00:00');
INSERT INTO VOO (ID_AERONAVE, ID_AEROPORTO_PARTIDA, ID_AEROPORTO_CHEGADA, HORARIO_PARTIDA, HORARIO_CHEGADA)
	VALUES (2, 3, 1, '2024-01-19 14:00:00', '2024-01-19 16:00:00');
INSERT INTO VOO (ID_AERONAVE, ID_AEROPORTO_PARTIDA, ID_AEROPORTO_CHEGADA, HORARIO_PARTIDA, HORARIO_CHEGADA)
	VALUES (3, 1, 1, '2024-01-19 12:00:00', '2024-01-19 14:00:00');
INSERT INTO VOO (ID_AERONAVE, ID_AEROPORTO_PARTIDA, ID_AEROPORTO_CHEGADA, HORARIO_PARTIDA, HORARIO_CHEGADA)
	VALUES (4, 4, 3, '2024-01-24 10:00:00', '2024-01-24 12:00:00');
    
/* ----------------------------------------------------[ESCALAS]--------------------------------------------------- */
INSERT INTO ESCALA (ID_AEROPORTO_SAIDA, HORARIO_SAIDA_ESCALA, ID_VOO) VALUES (1, '2024-01-19 15:00:00', 3); -- Escala com saída em CONGONHAS (AEROPORTO 1)
INSERT INTO ESCALA (ID_AEROPORTO_SAIDA, HORARIO_SAIDA_ESCALA, ID_VOO) VALUES (2, '2024-01-19 13:00:00', 4); -- Escala com saída em GUARULHOS (AEROPORTO 2)
INSERT INTO ESCALA (ID_AEROPORTO_SAIDA, HORARIO_SAIDA_ESCALA, ID_VOO) VALUES (2, '2024-01-24 11:00:00', 5); -- Escala com saída em GUARULHOS (AEROPORTO 2)

/* -----------------------------------------------------[MALAS]---------------------------------------------------- */
INSERT INTO MALA (ID_CLIENTE_DONO, PESO_MALA, ID_VOO) VALUES (1, 45, 1); -- MALA CLIENTE 1, VÔO 1
INSERT INTO MALA (ID_CLIENTE_DONO, PESO_MALA, ID_VOO) VALUES (1, 32, 1); -- MALA CLIENTE 1, VÔO 1
INSERT INTO MALA (ID_CLIENTE_DONO, PESO_MALA, ID_VOO) VALUES (2, 27, 2); -- MALA CLIENTE 2, VÔO 2
INSERT INTO MALA (ID_CLIENTE_DONO, PESO_MALA, ID_VOO) VALUES (3, 15, 3); -- MALA CLIENTE 3, VÔO 3
INSERT INTO MALA (ID_CLIENTE_DONO, PESO_MALA, ID_VOO) VALUES (4, 89, 4); -- MALA CLIENTE 4, VÔO 4

/* ---------------------------------------------------[PASSAGENS]-------------------------------------------------- */
INSERT INTO PASSAGEM (ID_POLTRONA, ID_CLIENTE, ID_VOO) VALUES (1, 1, 1); -- PASSAGEM POLTRONA 1, CLIENTE 1, VÔO 1
INSERT INTO PASSAGEM (ID_POLTRONA, ID_CLIENTE, ID_VOO) VALUES (7, 2, 2); -- PASSAGEM POLTRONA 7, CLIENTE 2, VÔO 2
INSERT INTO PASSAGEM (ID_POLTRONA, ID_CLIENTE, ID_VOO) VALUES (10, 3, 3); -- PASSAGEM POLTRONA 10, CLIENTE 3, VÔO 3
INSERT INTO PASSAGEM (ID_POLTRONA, ID_CLIENTE, ID_VOO) VALUES (16, 4, 4); -- PASSAGEM POLTRONA 16, CLIENTE 4, VÔO 4
INSERT INTO PASSAGEM (ID_POLTRONA, ID_CLIENTE, ID_VOO) VALUES (18, 2, 4); -- PASSAGEM POLTRONA 18, CLIENTE 2, VÔO 5